pipeline {
  agent any

  environment {
    NODE_ENV = 'test'
    PORT = '4000'
    MONGO_URI = credentials('MONGO_URI')
    CLDN_NAME = credentials('CLDN_NAME')
    CLDN_API_KEY = credentials('CLDN_API_KEY')
    CLDN_API_SECRET = credentials('CLDN_API_SECRET')
    JWT_SECRET = credentials('JWT_SECRET')
  }

  stages {
    stage('Install Dependencies') {
      steps {
        echo 'Installing backend dependencies...'
        dir('backend') {
          bat 'npm install'
        }
      }
    }
    
    stage('Run Tests') {
      steps {
        echo 'Running backend tests...'
        dir('backend') {
          bat 'npm test '
        }
      }
    }
    
    stage('Build') {
      steps {
        echo 'Building backend...'
        dir('backend') {
          bat 'npm run build'
        }
      }
    }
  }
  
  post {
    always {
      echo 'Cleaning up...'
    }
    success {
      echo 'Pipeline succeeded!'
    }
    failure {
      echo 'Pipeline failed!'
    }
  }
}
